# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Movie' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

    pod 'RxSwift',    	'~> 3.0'
    pod 'RxCocoa',    	'~> 3.0'
    pod 'Alamofire', 	  '~> 4.3'
    pod 'SnapKit',      '~> 3.0.2'

  target 'MovieTests' do
  
    inherit! :search_paths
    pod 'RxBlocking', 	'~> 3.0'
    pod 'RxTest',     	'~> 3.0'

  end

end
