# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'So-Vocabulary' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for So-Vocabulary
  pod 'Alamofire', '~> 4.5.0'
  pod 'SnapKit', '~> 3.2.0'
  
end
