# Uncomment the next line to define a global platform for your project
#platform :ios, '9.0'

target 'So-GG' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for So-GG
  pod 'RxSwift'
  pod 'Moya/RxSwift'
  pod 'ReachabilitySwift'
#  pod 'SnapKit'
  pod 'RxCocoa'
  pod 'NSObject+Rx'
  pod 'SwiftyJSON'
  pod 'Kingfisher'
end
